import type { Metadata } from "next";
import { LegalShell, LegalSection, LegalList } from "../../../components/LegalShell";

export const metadata: Metadata = {
  title: "Terms of Service | Vertofi",
  description:
    "Vertofi Terms of Service — the agreement governing use of Vertofi's accounting, GST, payroll, banking, AI financial-intelligence and WhatsApp Business Platform services.",
  alternates: { canonical: "/legal/terms" },
  robots: { index: true, follow: true },
  openGraph: { title: "Terms of Service | Vertofi", type: "website", url: "https://vertofi.com/legal/terms" },
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      updated="June 16, 2026"
      intro={
        <p>
          These Terms of Service (&ldquo;Terms&rdquo;) form a binding agreement between you and Vertofi and
          govern your access to and use of the Vertofi platform, websites, APIs, mobile experiences and our
          WhatsApp Business Platform integration (collectively, the &ldquo;Services&rdquo;). By creating an
          account or using the Services, you agree to these Terms. If you are using the Services on behalf of a
          business, you represent that you are authorised to bind that business.
        </p>
      }
    >
      <LegalSection id="definitions" heading="1. Definitions">
        <p>
          &ldquo;Vertofi&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; means the operator of the Services.
          &ldquo;You&rdquo; or &ldquo;User&rdquo; means the individual or business using the Services.
          &ldquo;Account&rdquo; means your registered workspace. &ldquo;Content&rdquo; means data, documents and
          information you submit. &ldquo;Subscription&rdquo; means a paid plan. &ldquo;AI Output&rdquo; means
          insights, drafts or recommendations generated by automated models.
        </p>
      </LegalSection>

      <LegalSection id="service-description" heading="2. Service Description">
        <p>
          Vertofi is a predictive accounting and financial-intelligence platform that helps businesses
          automate accounting, generate GST-compliant invoices and statutory documents, connect bank data,
          manage payroll and inventory, monitor compliance, and receive AI-assisted insights — including via
          WhatsApp. Features and availability may evolve over time.
        </p>
      </LegalSection>

      <LegalSection id="eligibility" heading="3. Eligibility">
        <p>
          You must be at least 18 years old and capable of forming a binding contract to use the Services. The
          Services are intended for businesses and professionals, primarily in India. You may not use the
          Services if you are barred from doing so under applicable law.
        </p>
      </LegalSection>

      <LegalSection id="user-obligations" heading="4. User Obligations">
        <LegalList
          items={[
            "Provide accurate, current and complete information and keep it updated;",
            "Maintain the confidentiality of your credentials and all activity under your Account;",
            "Use the Services only for lawful business purposes and in compliance with applicable law;",
            "Obtain all necessary consents from individuals (e.g. employees, customers) whose data you submit; and",
            "Promptly notify us of any unauthorised use or security incident affecting your Account.",
          ]}
        />
      </LegalSection>

      <LegalSection id="accuracy" heading="5. Accuracy of Financial Information">
        <p>
          You are solely responsible for the accuracy, completeness and timeliness of the source data you
          enter or connect (including bank, GST, invoice, payroll and accounting data). Vertofi automates and
          assists, but you must review and approve invoices, entries, filings and reports before relying on or
          submitting them. Vertofi is not responsible for outcomes resulting from inaccurate, incomplete or
          untimely data provided by you or your connected sources.
        </p>
      </LegalSection>

      <LegalSection id="subscription" heading="6. Subscription Terms">
        <p>
          Certain features require a paid Subscription. Subscriptions are offered on monthly or annual billing
          cycles and may include a free trial. Plan features, limits and prices are described at the point of
          purchase. We may change plans or pricing prospectively with notice; changes do not affect the
          current paid term.
        </p>
      </LegalSection>

      <LegalSection id="billing" heading="7. Billing and Payment Terms">
        <p>
          Subscriptions are billed in advance through our payment processor (such as Razorpay) via the method
          or auto-pay mandate you authorise. Fees are stated exclusive of taxes; applicable GST and other taxes
          are added as required by law. You authorise recurring charges for renewals until you cancel. If a
          payment fails, we may suspend paid features until the amount due is settled. You are responsible for
          providing valid, current payment information.
        </p>
      </LegalSection>

      <LegalSection id="cancellation" heading="8. Cancellation Terms">
        <p>
          You may cancel your Subscription at any time from your account or by contacting{" "}
          <a href="mailto:info@vertofi.com">info@vertofi.com</a>. Cancellation stops future renewals; access to
          paid features continues until the end of the current paid period, after which the Account may revert
          to a limited or read-only state. See our <a href="/legal/refunds">Refund Policy</a> for details.
        </p>
      </LegalSection>

      <LegalSection id="refunds" heading="9. Refund Policy">
        <p>
          Except where required by law, fees are generally non-refundable, and partial billing periods are not
          pro-rated upon cancellation. Specific eligibility, exclusions and the process for refunds are set out
          in our <a href="/legal/refunds">Refund &amp; Cancellation Policy</a>, which forms part of these Terms.
        </p>
      </LegalSection>

      <LegalSection id="gst" heading="10. GST Implications">
        <p>
          You are responsible for determining and meeting your own GST registration, invoicing, filing and
          payment obligations. Vertofi&rsquo;s GST features (including GSTIN lookup, HSN/SAC suggestions,
          e-invoice/e-way bill support and reconciliation) are tools to assist you and do not replace your
          obligation to verify and file correctly. Tax positions are subject to applicable laws, notifications
          and your professional advisor&rsquo;s guidance.
        </p>
      </LegalSection>

      <LegalSection id="ip" heading="11. Intellectual Property">
        <p>
          The Services, including all software, models, designs, text, and trademarks, are owned by Vertofi or
          its licensors and are protected by intellectual-property laws. We grant you a limited, non-exclusive,
          non-transferable, revocable licence to use the Services during your subscription. You may not copy,
          modify, reverse-engineer, resell or create derivative works from the Services except as permitted by
          law.
        </p>
      </LegalSection>

      <LegalSection id="data-ownership" heading="12. Data Ownership">
        <p>
          As between you and Vertofi, you retain all rights to your Content. You grant Vertofi a limited
          licence to host, process and use your Content solely to provide, secure and improve the Services and
          as described in our <a href="/legal/privacy">Privacy Policy</a>. We may use aggregated, anonymised
          data that does not identify you or your business to improve the Services and generate benchmarks.
        </p>
      </LegalSection>

      <LegalSection id="acceptable-use" heading="13. Acceptable Use Policy">
        <p>You agree not to:</p>
        <LegalList
          items={[
            "Use the Services for unlawful, fraudulent, or misleading purposes, including tax evasion or money laundering;",
            "Upload malware, attempt to breach security, or access data belonging to another organisation;",
            "Interfere with, overload, or disrupt the Services or related infrastructure;",
            "Use automated means to scrape or extract data except via permitted APIs;",
            "Infringe the intellectual-property or privacy rights of others; or",
            "Misuse the WhatsApp integration to send spam or content that violates Meta/WhatsApp policies.",
          ]}
        />
      </LegalSection>

      <LegalSection id="availability" heading="14. Service Availability">
        <p>
          We strive to keep the Services available and reliable but do not guarantee uninterrupted or
          error-free operation. The Services may be temporarily unavailable for maintenance, updates, or
          factors beyond our control. We may modify, suspend or discontinue features with reasonable notice
          where practicable.
        </p>
      </LegalSection>

      <LegalSection id="third-party" heading="15. Third-Party Integrations">
        <p>
          The Services integrate with third parties such as the WhatsApp Business Platform (Meta), payment
          processors, GST Suvidha Providers, the GST Network, and RBI-licensed Account Aggregators and banking
          partners. Your use of those integrations may be subject to the third party&rsquo;s own terms and
          policies. We are not responsible for third-party services, and availability of an integration may
          change.
        </p>
      </LegalSection>

      <LegalSection id="financial-disclaimer" heading="16. Disclaimer Regarding Financial Advice">
        <p>
          <strong>Vertofi is a software platform, not a bank, lender, payment system operator, registered
          investment adviser, chartered accountant, tax practitioner, or law firm.</strong> Nothing in the
          Services constitutes professional financial, tax, legal, accounting or investment advice. Information
          and reports are provided for your business&rsquo;s informational use only. You should consult a
          qualified professional before making decisions, and you remain solely responsible for your business
          decisions and statutory compliance filings.
        </p>
      </LegalSection>

      <LegalSection id="ai-disclaimer" heading="17. AI-Generated Recommendation Disclaimer">
        <p>
          The Services use artificial intelligence to digitise documents, classify and draft entries, suggest
          tax treatments, and generate insights and recommendations (&ldquo;AI Output&rdquo;). AI Output is
          probabilistic, may be incomplete or inaccurate, and must be independently reviewed and verified by
          you before reliance, submission or filing. AI Output does not constitute professional advice and is
          provided &ldquo;as is&rdquo; without warranty. You are responsible for all entries, approvals and
          filings made from your Account.
        </p>
      </LegalSection>

      <LegalSection id="warranty-disclaimer" heading="18. Warranties and Disclaimer">
        <p>
          Except as expressly stated in a separate written agreement, the Services are provided &ldquo;as
          is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, whether express, implied or
          statutory, including implied warranties of merchantability, fitness for a particular purpose, and
          non-infringement, to the maximum extent permitted by law.
        </p>
      </LegalSection>

      <LegalSection id="liability" heading="19. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, Vertofi and its affiliates, officers, employees and partners
          will not be liable for any indirect, incidental, special, consequential, exemplary or punitive
          damages, or for any loss of profits, revenue, data, goodwill, or business, arising out of or related
          to the Services. Our total aggregate liability for any claim arising out of or relating to the
          Services will not exceed the amount you paid to Vertofi for the Services in the twelve (12) months
          preceding the event giving rise to the claim.
        </p>
      </LegalSection>

      <LegalSection id="indemnification" heading="20. Indemnification">
        <p>
          You agree to indemnify and hold harmless Vertofi and its affiliates from and against any claims,
          liabilities, damages, losses and expenses (including reasonable legal fees) arising out of your
          Content, your use of the Services, your violation of these Terms or applicable law, or your
          infringement of any third-party right.
        </p>
      </LegalSection>

      <LegalSection id="termination" heading="21. Suspension and Termination">
        <p>
          You may stop using the Services at any time. We may suspend or terminate your access, with or
          without notice, if you breach these Terms, fail to pay fees, use the Services unlawfully, or create
          risk or legal exposure for Vertofi or others. Upon termination, your right to use the Services ceases.
          We will make your data available for export for a reasonable period unless prohibited by law, after
          which it may be deleted subject to statutory retention requirements described in our{" "}
          <a href="/legal/data-deletion">Data Deletion</a> page.
        </p>
      </LegalSection>

      <LegalSection id="governing-law" heading="22. Governing Law">
        <p>
          These Terms are governed by the laws of India, without regard to conflict-of-laws principles.
          Subject to the arbitration provision below, the courts at the seat of Vertofi&rsquo;s registered
          office in India shall have exclusive jurisdiction.
        </p>
      </LegalSection>

      <LegalSection id="arbitration" heading="23. Arbitration and Dispute Resolution">
        <p>
          The parties will first attempt to resolve any dispute amicably. Any dispute not resolved within
          thirty (30) days shall be referred to and finally resolved by arbitration under the Arbitration and
          Conciliation Act, 1996, by a sole arbitrator appointed by mutual agreement. The seat and venue of
          arbitration shall be in India, the language shall be English, and the award shall be final and
          binding. Nothing prevents either party from seeking interim relief from a court of competent
          jurisdiction.
        </p>
      </LegalSection>

      <LegalSection id="changes" heading="24. Changes to These Terms">
        <p>
          We may update these Terms from time to time. We will post the updated Terms here with a revised
          &ldquo;Last updated&rdquo; date and, where appropriate, provide additional notice. Continued use of
          the Services after an update constitutes acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection id="contact" heading="25. Contact Information">
        <p>
          Questions about these Terms? Email <a href="mailto:info@vertofi.com">info@vertofi.com</a>, or{" "}
          <a href="mailto:privacy@vertofi.com">privacy@vertofi.com</a> for privacy and data matters.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
